### Import the package

In [1]:
import numpy as np

### Create array

In [4]:
# 1 dimension array
a = np.array([1, 2, 4])
print(a)

[1 2 4]


In [5]:
# 2 dimensional array
b = np.array([[1.0, 2.9, 3.0], [2, 4.5, 6.1]])
print(b)

[[1.  2.9 3. ]
 [2.  4.5 6.1]]


In [9]:
# Get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [8]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
# Get type
print(a.dtype) # this is to get the type of object inside array
print(type(a)) # this is to get the type of object which is the array

int32
<class 'numpy.ndarray'>


### Access the values inside array

In [15]:
a = np.array([[1,2,3,4,5,6,7,8], [9,10,11,12,13,14,15,16]])
print(a)
print(a.shape)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
(2, 8)


In [18]:
# [row, column]
print(a[0, 7]) # 8
print(a[-1, -2]) # 15

8
15


In [21]:
# get specific column
print(a[:,1])

[ 2 10]


In [24]:
# get specific row
print(a[1,:])

[ 9 10 11 12 13 14 15 16]


In [31]:
# using fancy index, to get 12, 13, 14
a[1, 3:6:1]

array([12, 13, 14])

In [32]:
# change a value
a[1,-1] = 100
print(a)

[[  1   2   3   4   5   6   7   8]
 [  9  10  11  12  13  14  15 100]]


In [34]:
# change multiple value
a[:, 2] = [555, 444]
print(a)

[[  1   2 555   4   5   6   7   8]
 [  9  10 444  12  13  14  15 100]]


### Initializing custom array

In [40]:
# 0 matrix
np.zeros([9,2])
#np.zeros((9,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [38]:
# 1 matrix
np.ones([3, 5], dtype='int16')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [46]:
# any other matrix
np.full([4,3], 99, dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [49]:
# get the shape of other array to create a new custom array
np.full_like(a, 12, dtype='int16')

array([[12, 12, 12, 12, 12, 12, 12, 12],
       [12, 12, 12, 12, 12, 12, 12, 12]], dtype=int16)

In [76]:
# create random matrix
print('Random number\n', np.random.rand(4,2,4))
print('\nRandom int\n', np.random.randint(low=23, high=56, size=[3,4], dtype='int16'))
print('\nRandom normal distribution\n', np.random.randn(2,5))
print('\nRandom sample to create new matrix using other matrix size\n', np.random.random_sample(a.shape))

Random number
 [[[0.19665967 0.23327488 0.48039522 0.96083758]
  [0.94422568 0.26978098 0.41475604 0.01363533]]

 [[0.70266616 0.76087073 0.40873544 0.96542417]
  [0.33807074 0.80790584 0.18489118 0.02087486]]

 [[0.17034837 0.817351   0.38714823 0.11256447]
  [0.54337307 0.02981029 0.56270616 0.35248232]]

 [[0.48558537 0.83626715 0.04136347 0.47045915]
  [0.12157349 0.96057839 0.76061505 0.14452503]]]

Random int
 [[54 29 50 55]
 [45 55 23 35]
 [46 45 27 51]]

Random normal distribution
 [[ 1.05324784  1.01747708 -0.70207634  0.84586704  1.05141431]
 [ 1.02764342  0.91130822  0.46461211  0.71418671  0.36375136]]

Random sample to create new matrix using other matrix size
 [[0.8985915  0.35247819 0.97025324 0.04769622 0.16402164 0.3978878
  0.28855192 0.85030599]
 [0.20928232 0.2476977  0.10726892 0.18225443 0.4879387  0.55311906
  0.0885919  0.99918437]]


In [78]:
# create identity matrix
print(np.identity(9))

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [86]:
# repeat array
x = np.array([[9,3,4,5],[3,4,1,2]])
np.repeat(x, 4, axis=0)

array([[9, 3, 4, 5],
       [9, 3, 4, 5],
       [9, 3, 4, 5],
       [9, 3, 4, 5],
       [3, 4, 1, 2],
       [3, 4, 1, 2],
       [3, 4, 1, 2],
       [3, 4, 1, 2]])

In [97]:
# create custom array
x = np.ones([5,5], dtype='int32')
x[1:-1,1:-1] = np.zeros([3,3])
x[2,2] = 9
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Copy array

In [99]:
a = np.array([9,9,8,8])
b = a.copy() # doing this prevent original array to be modified unintentionaly
b[2] = 90
print(a)

[9 9 8 8]


### Linear Algebra

In [103]:
a = np.full([2,3], 6)
print(a)

b = np.full([3,2], 5)
print(b)

# row * col
print(np.matmul(a, b))
print(np.matmul(b, a))

[[6 6 6]
 [6 6 6]]
[[5 5]
 [5 5]
 [5 5]]
[[90 90]
 [90 90]]
[[60 60 60]
 [60 60 60]
 [60 60 60]]


In [105]:
# find determinant
a= np.identity(8)
print(np.linalg.det(a))

1.0


### Statistics

In [109]:
a = np.random.rand(9,5)
print(a)
np.min(a)

[[0.89538016 0.77328451 0.44245372 0.10050612 0.25457724]
 [0.42373022 0.96991767 0.2839498  0.80069852 0.03405498]
 [0.12255632 0.18139596 0.59416412 0.51345192 0.9498027 ]
 [0.57299208 0.02415436 0.48436222 0.85282333 0.12281402]
 [0.79253    0.46957819 0.62124693 0.52912715 0.93561973]
 [0.71122715 0.64747183 0.06653333 0.16198026 0.70035383]
 [0.23130516 0.74754933 0.78162877 0.05777389 0.17433583]
 [0.50732327 0.00858171 0.80594607 0.30493616 0.66285044]
 [0.90587843 0.98990726 0.29115421 0.31160109 0.00327393]]


0.003273929299194789

In [112]:
np.max(a, axis=1)

array([0.89538016, 0.96991767, 0.9498027 , 0.85282333, 0.93561973,
       0.71122715, 0.78162877, 0.80594607, 0.98990726])

In [113]:
np.mean(a, axis=1)

array([0.49324035, 0.50247024, 0.4722742 , 0.4114292 , 0.6696204 ,
       0.45751328, 0.39851859, 0.45792753, 0.50036298])

In [111]:
np.sum(a)

21.81678389439368

### Reorganizing arrays

In [117]:
a = np.random.randint(30, 89, [5,8])
print(a)

[[53 30 82 74 72 61 39 56]
 [56 80 66 88 32 51 77 52]
 [30 49 69 71 36 49 30 56]
 [86 39 65 75 78 45 70 46]
 [54 47 55 43 73 61 41 73]]


In [118]:
print(a.shape)

(5, 8)


In [119]:
# reshape
a.reshape([4,10])

array([[53, 30, 82, 74, 72, 61, 39, 56, 56, 80],
       [66, 88, 32, 51, 77, 52, 30, 49, 69, 71],
       [36, 49, 30, 56, 86, 39, 65, 75, 78, 45],
       [70, 46, 54, 47, 55, 43, 73, 61, 41, 73]])

In [121]:
a.reshape([2,4,5])

array([[[53, 30, 82, 74, 72],
        [61, 39, 56, 56, 80],
        [66, 88, 32, 51, 77],
        [52, 30, 49, 69, 71]],

       [[36, 49, 30, 56, 86],
        [39, 65, 75, 78, 45],
        [70, 46, 54, 47, 55],
        [43, 73, 61, 41, 73]]])

In [133]:
# vertical stack array
v1 = np.array([[3,5,6,7,3],[4,5,3,3,2]])
v2 = np.array([[5,3,2,4,5],[3,3,2,2,2]])
np.vstack([v1, v2, v2])

array([[3, 5, 6, 7, 3],
       [4, 5, 3, 3, 2],
       [5, 3, 2, 4, 5],
       [3, 3, 2, 2, 2],
       [5, 3, 2, 4, 5],
       [3, 3, 2, 2, 2]])

In [134]:
# horizontal stack
np.hstack([v1, v2])

array([[3, 5, 6, 7, 3, 5, 3, 2, 4, 5],
       [4, 5, 3, 3, 2, 3, 3, 2, 2, 2]])

### Indexing

In [138]:
# single criteria
v1[v1 < 4]

array([3, 3, 3, 3, 2])

In [146]:
# multiple criteria
print(v1)
print(np.logical_and(v1 > 3, v1 <= 5))

[[3 5 6 7 3]
 [4 5 3 3 2]]
[[False  True False False False]
 [ True  True False False False]]


In [152]:
# creating fancy stuf
x = np.array([x for x in range(1,31)]).reshape(6,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [154]:
# get 11, 12, 16, 17
x[2:4, :2]

array([[11, 12],
       [16, 17]])

In [177]:
# get 2, 8, 14, 20
c = np.zeros([6,5], dtype='bool')
c[:4,1:] = np.identity(4, dtype='bool')
print('criteria: \n', c)

print('\nFiltered x:\n', x[c])
# OR
print(x[[0,1,2,3], [1,2,3,4]])

criteria: 
 [[False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]
 [False False False False False]
 [False False False False False]]

Filtered x:
 [ 2  8 14 20]
[ 2  8 14 20]


In [182]:
# get 4,5,24,25,29,30
x[[0, -2,-1],-2:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])